const AUTH = {
  TOKEN: 'AUTH_TOKEN'
};

const COMPONENT = {
  ON_ACCOUNTS_SUCCESS: 'ON_ACCOUNTS_SUCCESS',
  ON_CATEGORIES_SUCCESS: 'ON_CATEGORIES_SUCCESS',
  ON_MERCHANTS_SUCCESS: 'ON_MERCHANTS_SUCCESS',
  ON_PLANNING_SUCCESS: 'ON_PLANNING_SUCCESS',
  ON_SPENDING_SUCCESS: 'ON_SPENDING_SUCCESS',
  ON_BUDGET_SUCCESS: 'ON_BUDGET_SUCCESS',
  ON_EXPENSE_SUCCESS: 'ON_EXPENSE_SUCCESS',
  ON_FEED_SUCCESS: 'ON_FEED_SUCCESS',
  ON_BILL_SUCCESS: 'ON_BILL_SUCCESS',
  ON_CARBON_SUCCESS: 'ON_CARBON_SUCCESS',
};

const TYPES = {
  AUTH,
  COMPONENT,
};

export default TYPES;
